export { Home } from './Home';
export { Login } from './Login';
export { Register } from './Register';
export { Dashboard } from './Dashboard';
export { AllDeals } from './AllDeals';
export { LeadManagement } from './LeadManagement';
export { Settings } from './Settings';
export { NotFound } from './NotFound';
export { DummyPage } from './DummyPage';
