/**
 * ┌─────────────────────────────────────────────────────────┐
 *  Browser Worker — Sets up MSW service worker
 * └─────────────────────────────────────────────────────────┘
 *
 * This creates the MSW service worker that intercepts fetch/XHR
 * requests in the browser. It is ONLY imported in development.
 *
 * The service worker file (mockServiceWorker.js) lives in public/
 * and was generated by: npx msw init public --save
 */

import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
